2022-03-14 11:06:41.295 INFO  [acme.Launcher@main] Starting Launcher using Java 1.8.0_281 on PC_ALVARO with PID 644 (C:\Users\alvar\Desktop\Universidad\DP2\Workspace-22.0\Frameworks\Acme-Framework-22.1\target\classes started by alvar in C:\Users\alvar\Desktop\Universidad\DP2\Workspace-22.0\Projects\Acme-Toolkits) 
2022-03-14 11:06:41.297 DEBUG [acme.Launcher@main] Running with Spring Boot v2.4.2, Spring v5.3.3 
2022-03-14 11:06:41.298 INFO  [acme.Launcher@main] The following profiles are active: development,populator 
2022-03-14 11:06:44.123 DEBUG [org.apache.jasper.servlet.JasperInitializer@main] Initializing Jasper for context [application] 
2022-03-14 11:06:45.893 ERROR [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean@main] Failed to initialize JPA EntityManagerFactory: @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List 
2022-03-14 11:06:45.894 WARN  [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List 
2022-03-14 11:06:45.950 ERROR [org.springframework.boot.SpringApplication@main] Application run failed at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List\nat org.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List
2022-03-14 11:06:45.952 ERROR [acme.Launcher@main] org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List\norg.hibernate.cfg.ToOneFkSecondPass.doSecondPass(ToOneFkSecondPass.java:97): @OneToOne or @ManyToOne on acme.entities.component.Component.Tools references an unknown entity: java.util.List 
2022-03-14 11:06:45.953 INFO  [acme.Launcher@main] The application log provides additional debugging messages! 
2022-03-14 11:06:46.965 DEBUG [acme.Launcher@main] Exit code = 1 
